data:extend{
    {
        type = "fluid",
        name = "rf-high-energy-antiprotons",
        icon = "__RealisticFusionAntimatter__/graphics/icons/high-energy-antiproton.png",
        icon_size = 64,
        default_temperature = 50000,
        max_temperature = 1.417e32,
        base_color = {1,1,1},
        flow_color = {1,1,1},
        gas_temperature = -270,
        auto_barrel = false
    },
    {
        type = "fluid",
        name = "rf-high-energy-positrons",
        icon = "__RealisticFusionAntimatter__/graphics/icons/high-energy-positron.png",
        icon_size = 64,
        default_temperature = 50000,
        max_temperature = 1.417e32,
        base_color = {1,1,1},
        flow_color = {1,1,1},
        gas_temperature = -270,
        auto_barrel = false
    },
    {
        type = "fluid",
        name = "rf-antiprotons",
        icon = "__RealisticFusionAntimatter__/graphics/icons/antiproton.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1.417e32,
        base_color = {1,1,1},
        flow_color = {1,1,1},
        gas_temperature = -270,
        auto_barrel = false
    },
    {
        type = "fluid",
        name = "rf-positrons",
        icon = "__RealisticFusionAntimatter__/graphics/icons/positron.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1.417e32,
        base_color = {1,1,1},
        flow_color = {1,1,1},
        gas_temperature = -270,
        auto_barrel = false
    },
    {
        type = "fluid",
        name = "rf-antihydrogen",
        icon = "__RealisticFusionAntimatter__/graphics/icons/antihydrogen.png",
        icon_size = 64, icon_mipmaps = 4,
        default_temperature = 15,
        max_temperature = 1000,
        base_color = {1,1,1},
        flow_color = {1,1,1},
        gas_temperature = -253,
        auto_barrel = false
    },

    {
        type = "fluid",
        name = "rf-hydrogen",
        icon = "__RealisticFusionAntimatter__/graphics/icons/hydrogen.png",
        icon_size = 64, icon_mipmaps = 4,
        default_temperature = 15,
        max_temperature = 1000,
        base_color = {1,1,1,0.5},
        flow_color = {1,1,1,0.5},
        gas_temperature = -253,
    },
    {
        type = "fluid",
        name = "rf-protons",
        icon = "__RealisticFusionAntimatter__/graphics/icons/proton.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1.417e32,
        base_color = {1,1,1},
        flow_color = {1,1,1},
        gas_temperature = -270,
    },
    {
        type = "fluid",
        name = "rf-electrons",
        icon = "__RealisticFusionAntimatter__/graphics/icons/electron.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1.417e32,
        base_color = {1,1,1},
        flow_color = {1,1,1},
        gas_temperature = -270,
    },
}