data:extend{
    {
        type = "item",
        name = "rf-particle-accelerator",
        order = "h[antimatter-power]-a[particle-accelerator]",
        --group = "production",
        subgroup = "energy",
        icon = "__RealisticFusionAntimatter__/graphics/particle-accelerator/accelerator-icon.png",
        icon_size = 64,
        stack_size = 1,
        place_result = "rf-particle-accelerator",
    },
    {
        type = "item",
        name = "rf-particle-decelerator",
        order = "h[antimatter-power]-a[particle-decelerator]",
        --group = "production",
        subgroup = "energy",
        icon = "__RealisticFusionAntimatter__/graphics/particle-accelerator/decelerator-icon.png",
        icon_size = 128,
        stack_size = 2,
        place_result = "rf-particle-decelerator",
    },
    {
        type = "item",
        name = "rf-antimatter-processor",
        order = "h[antimatter-power]-b[antimatter-processor]",
        --group = "production",
        subgroup = "energy",
        icon = "__RealisticFusionAntimatter__/graphics/icons/antimatter-processor.png",
        icon_size = 64,
        stack_size = 10,
        place_result = "rf-antimatter-processor",
        localised_description = {"rf.antimatter-processor", "rf-antiprotons", "rf-positrons", "rf-antihydrogen"},
    },
    {
        type = "item",
        name = "rf-antimatter-reactor",
        order = "h[antimatter-power]-c[antimatter-reactor]",
        --group = "production",
        subgroup = "energy",
        icon = "__RealisticFusionAntimatter__/graphics/icons/antimatter-reactor.png",
        icon_size = 64,
        stack_size = 1,
        place_result = "rf-antimatter-reactor",
    },
    {
        type = "item",
        name = "rf-matter-antimatter-fuel-cell",
        icon = "__RealisticFusionAntimatter__/graphics/particle-accelerator/matter-antimatter-fuel-cell.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "intermediate-product",
        burnt_result = "rf-matter-antimatter-fuel-cell-empty",
        order = "r[uranium-processing]-a[uranium-fuel-cell]za",
        fuel_category = "rf-matter-antimatter", --hydrogen density is 0.0899mg/ml, x47.784... (ml/ingame unit) = ~4.2682722mg/u
        fuel_value = "15TJ",                     --E=mc² since 100% of the mass is converted into usable energy in matter-antimater annihilation
        stack_size = 20                          --that means E = (4.2682722/1000000)*299 792 458² = ~382GJ *40 because there's 40u of hydrogen and antihydrogen involved = ~15TJ
    },
    {
        type = "item",
        name = "rf-matter-antimatter-fuel-cell-empty",
        icon = "__RealisticFusionAntimatter__/graphics/particle-accelerator/empty-matter-antimatter-fuel-cell.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "intermediate-product",
        order = "r[uranium-processing]-a[uranium-fuel-cell]z",
        stack_size = 20
    },
    { --if you're changing this don't forget to also paste it to the SE patch when you're done
      type = "tool",
      name = "rf-antimatter-science-pack",
      icon = "__RealisticFusionAntimatter__/graphics/icons/antimatter-science-pack.png",
      icon_size = 64, icon_mipmaps = 4,
      subgroup = "science-pack",
      order = "zz",
      stack_size = 200,
      durability = 1,
      durability_description_key = "description.science-pack-remaining-amount-key",
      durability_description_value = "description.science-pack-remaining-amount-value"
    },
}